//Constants.cs
using System.Collections.Generic;

namespace BirthdayReminderMod
{
    public static class Constants
    {
        public static readonly Dictionary<string, int> ItemNameToIdMap = new Dictionary<string, int>
        {
            { "Coconut", 88 },
            { "Sunflower", 421 },
            { "Fruit Salad", 610 },
            { "Pink Cake", 221 },
            { "Amethyst", 66 },
            { "Banana Pudding", 904 },
            { "Pumpkin", 276 },
            { "Blackberry Cobbler", 611 },
            { "Chocolate Cake", 220 },
            { "Spicy Eel", 226 },
            { "Pufferfish", 128 },
            { "Aquamarine", 62 },
            { "Cloth", 428 },
            { "Emerald", 60 },
            { "Jade", 70 },
            { "Parrot Egg", 832 },
            { "Ruby", 64 },
            { "Survival Burger", 241 },
            { "Topaz", 68 },
            { "Wool", 440 },
            { "Goat Cheese", 426 },
            { "Poppyseed Muffin", 651 },
            { "Salad", 196 },
            { "Stir Fry", 606 },
            { "Truffle", 430 },
            { "Vegetable Medley", 200 },
            { "Wine", 348 },
            { "Battery Pack", 787 },
            { "Cauliflower", 190 },
            { "Cheese Cauliflower", 197 },
            { "Diamond", 72 },
            { "Gold Bar", 336 },
            { "Iridium Bar", 337 },
            { "Miner's Treat", 243 },
            { "Pepper Poppers", 215 },
            { "Radioactive Bar", 910 },
            { "Rhubarb Pie", 222 },
            { "Strawberry", 400 },
            { "Melon", 254 },
            { "Poppy", 376 },
            { "Red Plate", 230 },
            { "Roots Platter", 244 },
            { "Sandfish", 164 },
            { "Tom Kha Soup", 218 },
            { "Complete Breakfast", 201 },
            { "Salmon Dinner", 212 },
            { "Crab Cakes", 732 },
            { "Duck Feather", 444 },
            { "Lobster", 715 },
            { "Pomegranate", 637 },
            { "Squid Ink", 814 },
            { "Coffee", 395 },
            { "Pickles", 342 },
            { "Super Meal", 237 },
            { "Truffle Oil", 432 },
            { "Cactus Fruit", 90 },
            { "Maple Bar", 731 },
            { "Pizza", 206 },
            { "Tigerseye", 562 },
            { "Frog Egg", 828 },
            { "Frozen Tear", 84 },
            { "Obsidian", 575 },
            { "Pumpkin Soup", 236 },
            { "Sashimi", 227 },
            { "Void Egg", 305 },
            { "Beer", 346 },
            { "Hot Pepper", 260 },
            { "Fish Taco", 213 },
            { "Green Tea", 614 },
            { "Summer Spangle", 593 },
            { "Tropical Curry", 907 },
            { "Artichoke Dip", 605 },
            { "Omni Geode", 749 },
            { "Bean Hotpot", 207 },
            { "Ice Cream", 233 },
            { "Rice Pudding", 232 },
            { "Beet", 284 },
            { "Fairy Rose", 595 },
            { "Stuffing", 239 },
            { "Tulip", 591 },
            { "Fried Mushroom", 205 },
            { "Leek", 20 },
            { "Escargot", 728 },
            { "Orange", 635 },
            { "Ancient Doll", 103 },
            { "Fairy Box", 1021 }, // Assuming custom item ID
            { "Plum Pudding", 604 },
            { "Crispy Bass", 214 },
            { "Eggplant Parmesan", 231 },
            { "Fried Eel", 225 },
            { "Pancakes", 211 },
            { "Roasted Hazelnuts", 607 },
            { "Autumn's Bounty", 235 },
            { "Glazed Yams", 208 },
            { "Dish o' The Sea", 242 },
            { "Yam", 280 },
            { "Farmer's Lunch", 240 },
            { "Pumpkin Pie", 608 },
            { "Mead", 459 },
            { "Pale Ale", 303 },
            { "Parsnip", 24 },
            { "Parsnip Soup", 199 },
            { "Pina Colada", 873 },
            { "Fried Calamari", 202 },
            { "Peach", 636 },
            { "Spaghetti", 224 },
            { "Cranberry Candy", 612 },
            { "Ginger Ale", 903 },
            { "Grape", 398 },
            { "Snail", 720 },
            { "Catfish", 143 },
            { "Octopus", 149 },
            { "Sea Cucumber", 154 },
            { "Sturgeon", 698 },
            { "Lava Eel", 162 },
            { "Lemon Stone", 554 },
            { "Monster Musk", 879 },
            { "Wild Horseradish", 16 },
            { "Mango", 834 },
            { "Ostrich Egg", 289 },
            { "Poi", 906 },
            { "Crocus", 418 },
            { "Daffodil", 18 },
            { "Mango Sticky Rice", 905 },
            { "Sweet Pea", 402 },
            { "Purple Mushroom", 422 },
            { "Solar Essence", 768 },
            { "Super Cucumber", 155 },
            { "Void Essence", 769 },
            { "Void Mayonnaise", 308 }
        };
    }
}
